### ISSUE TITLE
File upload with CSV files

### ISSUE THREAD

**Issue by maximosipov** [baasbox/baasbox#632]
Hi Folks,

Uploading CSV file from Android client on version 9.0 fails and seem to leave the database in inconsistent state (Dashboard Files shows large number of files, but these are not displayed in the files list). The error message is below.

Kind regards,
Max

2015-01-15 19:46:02.370+0000,DEBUG,Upload failed: Error{error=class com.baasbox.android.BaasServerException :{"result":"error","message":"java.lang.Exception: Error parsing uploaded file\n\tat com.baasbox.controllers.File.storeFile(File.java:240)\n\t
at Routes$$anonfun$routes$1$$anonfun$applyOrElse$100$$anonfun$apply$100.apply(routes_routing.scala:1494)\n\t
at Routes$$anonfun$routes$1$$anonfun$applyOrElse$100$$anonfun$apply$100.apply(routes_routing.scala:1494)\n\t
at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)\n\t
at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)\n\t
at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)\n\t
at play.GlobalSettings$1.call(GlobalSettings.java:64)\n\t
at com.baasbox.controllers.actions.filters.ConnectToDBFilter.call(ConnectToDBFilter.java:81)\n\t
at com.baasbox.controllers.actions.filters.UserCredentialWrapFilter.call(UserCredentialWrapFilter.java:74)\n\t
at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)\n\t
at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)\n\t
at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)\n\t
at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)\n\t
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)\n\t
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)\n\t
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)\n\t
at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)\n\t
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)\n\t
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)\n\t
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\t
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\t
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\t
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #18\n\t
at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.executeSaveRecord(ODatabaseRecordAbstract.java:1161)\n\t
at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:84)\n\t
at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:322)\n\t
at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:309)\n\t
at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:40)\n\t
at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.linkToStream(ORecordSerializerCSVAbstract.java:129)\n\
tat com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.fieldToStream(ORecordSerializerCSVAbstract.java:352)\n\t
at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toString(ORecordSerializerSchemaAware2CSV.java:495)\n\t
at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toStream(ORecordSerializerStringAbstract.java:673)\n\t
at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toStream(ORecordSerializerSchemaAware2CSV.java:258)\n\t
at com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.toStream(ORecordSchemaAwareAbstract.java:420)\n\t
at com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.toStream(ORecordSchemaAwareAbstract.java:415)\n\t
at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:423)\n\t
at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.executeSaveRecord(ODatabaseRecordAbstract.java:1072)\n\t
at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:84)\n\t
at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:322)\n\t
at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:40)\n\t
at com.orientechnologies.orient.core.record.ORecordAbstract.save(ORecordAbstract.java:335)\n\t
at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1439)\n\t
at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1428)\n\t
at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1417)\n\t
at com.baasbox.dao.NodeDao.save(NodeDao.java:159)\n\t
at com.baasbox.dao.FileDao.save(FileDao.java:101)\n\t
at com.baasbox.service.storage.FileService.createFile(FileService.java:86)\n\t
at com.baasbox.service.storage.FileService.createFile(FileService.java:94)\n\t
at com.baasbox.controllers.File.storeFile(File.java:226)\n\t
... 22 more
\nCaused by: java.lang.NullPointerException\n\t
at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.get(OLocalHashTable.java:385)\n\t
at com.orientechnologies.orient.core.index.engine.OLocalHashTableIndexEngine.get(OLocalHashTableIndexEngine.java:155)\n\t
at com.orientechnologies.orient.core.index.OIndexFullText.put(OIndexFullText.java:94)\n\t
at com.orientechnologies.orient.core.index.OIndexFullText.put(OIndexFullText.java:40)\n\t
at com.orientechnologies.orient.core.tx.OTransactionNoTx.addIndexEntry(OTransactionNoTx.java:188)\n\t
at com.orientechnologies.orient.core.index.OIndexTxAware.put(OIndexTxAware.java:94)\n\t
at com.orientechnologies.orient.core.index.OIndexTxAware.put(OIndexTxAware.java:38)\n\t
at com.orientechnologies.orient.core.index.OClassIndexManager.addIndexesEntries(OClassIndexManager.java:98)\n\t
at com.orientechnologies.orient.core.index.OClassIndexManager.onRecordAfterCreate(OClassIndexManager.java:73)\n\t
at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:240)\n\t
at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.callbackHooks(ODatabaseRecordAbstract.java:1466)\n\t
at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.executeSaveRecord(ODatabaseRecordAbstract.java:1138)\n\t
... 47 more
\n","resource":"/file","method":"POST","request_header":{"X-BAASBOX-APPCODE":["XXX"],"Connection":["Keep-Alive"],"Content-Length":["617"],"X-BB-SESSION":["XXX"],"Content-Type":["multipart/form-data; boundary=14aef218e73"],"Accept-Encoding":["gzip"],"User-Agent":["BaasBox AndroidSDK/0.9.0"],"Host":["XXX"]},"API_version":"0.9.0","http_code":500}} ()

**Comment by giastfader** [comment]
It seems that there is a problem with the OrientDB FullText index.
The file should be stored, but this exception is weird.
Can you send me the file that causes the problem, please?
I will try to isolate the problem, and in case I'will open an issue on OrientDB.

**Comment by maximosipov** [comment]
Sure, the example file is attached.

**Comment by giastfader** [comment]
Sorry,  I don't see any file. I think that github has eliminated it from the email

**Comment by maximosipov** [comment]
Well, the file is actually really simple, like below (one line with date
and 3 values):

cat pebble-msg-analysis-2015-01-15-10.csv
2015-01-15 09:51:35.384+0000,0.0,0.06896551724137931,0.9310344827586207

**Comment by giastfader** [comment]
I created a file with the line you posted and it worked.
Is that file to throw the exception?

**Comment by maximosipov** [comment]
Strange, it fails on my private instance. Do you have a sandbox
installation somewhere I could test it on?

**Comment by giastfader** [comment]
Sure.
Write me at claudio.github-at-gmail.com and I will provide you the access info.
