### ISSUE TITLE
Launching app with latest updates

### ISSUE THREAD

**Issue by guiduroy** [baasbox/baasbox#748]
I saw that the latest version on the master branch has fixed the issue concerning the push notification. How can i obtain the Jar library necessary to import to android studio for my app ? i currently have "baasbox-android-0.9.2.jar" from the stable release imported to my project which doesn't include the fix i imagine. I have already built the master branch but can't find the right Jar file to import ...

Thank you

edit: or do i have to update somehow the baasbox server to get the latest version (0.9.4)?

**Comment by giastfader** [comment]
That was a server error. You only need to upgrade the server to the latest nightly build

**Comment by guiduroy** [comment]
i now currently have 'v. 0.9.4-20150427-nightly' as the server version but my app still crashes when i try to enable push notification with the 'java.lang.RuntimeException: java.lang.IllegalArgumentException: argument 1 should have type java.lang.String[], got java.lang.String' error...

Any further thoughts ?

**Comment by giastfader** [comment]
This seems another problem. Can you give us more details? How did you enable push notifications? Can you post the stacktrace? 
Thanks

**Comment by guiduroy** [comment]
java.lang.RuntimeException: java.lang.IllegalArgumentException: wrong number of arguments; expected 1, got 2
            at com.baasbox.android.ExceptionHandler$1.onError(ExceptionHandler.java:33)
            at com.baasbox.android.impl.Dispatcher$Worker.run(Dispatcher.java:174)
     Caused by: java.lang.IllegalArgumentException: wrong number of arguments; expected 1, got 2
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.baasbox.android.impl.GCMWrapper.registerGCM0(GCMWrapper.java:87)
            at com.baasbox.android.impl.GCMWrapper.registerGCM(GCMWrapper.java:77)
            at com.baasbox.android.BaasCloudMessagingService.registerWithGoogle(BaasCloudMessagingService.java:85)
            at com.baasbox.android.BaasCloudMessagingService.access$200(BaasCloudMessagingService.java:22)
            at com.baasbox.android.BaasCloudMessagingService$RegisterMessaging.asyncCall(BaasCloudMessagingService.java:370)
            at com.baasbox.android.BaasCloudMessagingService$RegisterMessaging.asyncCall(BaasCloudMessagingService.java:346)
            at com.baasbox.android.impl.Task.execute(Task.java:189)
            at com.baasbox.android.impl.Dispatcher$Worker.run(Dispatcher.java:170)

**Comment by guiduroy** [comment]
The error comes from my call to setpushid but only crashes when I call baasbox.enableSync()

**Comment by giastfader** [comment]
Ah, I see. This can be a SDK problem, you should open an issue here https://github.com/baasbox/Android-SDK

**Comment by guiduroy** [comment]
eliantor seems to have pushed a commit onto the master which fixes the specific issue, https://github.com/baasbox/Android-SDK/issues/40 but how to do i build the android sdk master branch from git to obtain the correct Jar library file ?
