### ISSUE TITLE
OConcurrentModificationException: Cannot UPDATE the record because the version is not the latest

### ISSUE THREAD

**Issue by sunset791** [baasbox/baasbox#765]
In my code, I use BaasBox iOS SDK to create 1 master document (say Order), 3 detail documents (say Order Item) and 3 links from Order to Order Items.
The following exception happens randomly. Sometimes it fails in creating only one link, sometimes in creating 2 of them, sometime it doesn't fail at all.

Error Domain=com.baasbox.error Code=-22222 "com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #11:180 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.updateRecord(OLocalPaginatedStorage.java:804)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.commitEntry(OLocalPaginatedStorage.java:2105)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.commit(OLocalPaginatedStorage.java:1097)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:469)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:148)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.commit(ODatabaseRecordTx.java:142)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.commit(ODatabaseRecordTx.java:113)
	at com.baasbox.db.DbHelper.commitTransaction(DbHelper.java:150)
	at com.baasbox.dao.LinkDao.createLink(LinkDao.java:70)
	at com.baasbox.service.storage.LinkService.createLink(LinkService.java:32)
	at com.baasbox.controllers.Link.createLink(Link.java:51)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$69$$anonfun$apply$69.apply(routes_routing.scala:1246)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$69$$anonfun$apply$69.apply(routes_routing.scala:1246)
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)
	at play.GlobalSettings$1.call(GlobalSettings.java:64)
	at com.baasbox.controllers.actions.filters.ConnectToDBFilter.call(ConnectToDBFilter.java:81)
	at com.baasbox.controllers.actions.filters.UserCredentialWrapFilter.call(UserCredentialWrapFilter.java:74)
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
" UserInfo=0x7fe01e02b1a0 {iOS SDK Version=0.8.4, NSLocalizedDescription=com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #11:180 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)

**Comment by giastfader** [comment]
Maybe into your code you start three asynchronous concurrent requests.
If so, you should "concatenate" them. I mean  as soon as one succeed the next one can start.
